### ISSUE TITLE
Added everyone in ske project link

### ISSUE THREAD

**Issue by Tezigudo** [Secret-Order/SKE19-Project-Archive#5]
`here` is a link of every project in SKE Programming1

https://ecourse.cpe.ku.ac.th/tpm/project/prog1-21f

**Comment by GToidZ** [comment]
The sole purpose of this repository is to link projects that are **open sourced** on Github, encouraging those who wanted to study code or apply coding practices to their projects.

**Therefore, I don't think this repository would link to places other than Github.**

**Comment by GToidZ** [comment]
I will update the repository description later so I could clear such misunderstanding.
